# Generated by Django 3.0.4 on 2020-07-18 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200703_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='canvas_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 54, 9, 826102), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
