# Generated by Django 3.0.4 on 2020-07-19 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200719_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='canvas_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 47, 39, 659077), verbose_name='date published'),
        ),
    ]
