# Generated by Django 3.0.4 on 2020-07-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200719_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='canvas',
            name='canvas_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 48, 55, 432493), verbose_name='date published'),
        ),
    ]
