# Generated by Django 3.0.4 on 2020-07-20 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='canvas_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 9, 59, 1, 113531), verbose_name='date published'),
        ),
    ]
