# Generated by Django 3.0.4 on 2020-07-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200720_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='canvas_published',
        ),
    ]
