# Generated by Django 3.0.4 on 2020-07-28 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20200720_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvas',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='category',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
