# Generated by Django 3.0.4 on 2020-07-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200728_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
